// AUTO:  ++++++++++++++++++++++
// AUTO:  version info automatically generated by tracker; generated by Johannes Gerstmayr
// AUTO:  last modified = 2025-07-09
// AUTO:  ++++++++++++++++++++++
namespace EXUstd {
 const char* exudynVersion = "1.10.0";
}
